- hosts: pull_mode_hosts
  user: vagrant
  sudo: yes

  vars:
        schedule: "5 * * * *"
        cron_user: vagrant
        logfile: /tmp/ansible-pull.log
        workdir: /tmp/
        repo_url: https://github.com/yutaka-j/ansible-pull-test.git
        
  tasks:
        - name: Install emacs
          action: apt pkg=emacs state=installed
        - name: Echo commans
          action: command /bin/echo Hello >> /tmp/echo.log
